name: Discord Bot

on:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Discord Bot
        run: |
          python bot.py

    timeout-minutes: 3
